<h1>--- Numpy ---</h1>

In [53]:
import numpy as np
arr = [23,26,25,4,2,6,15,48,58]
arr_np = np.array(arr)
arr_np

array([23, 26, 25,  4,  2,  6, 15, 48, 58])

<h5>Calculating the average of arrays: </h5>

In [54]:
exam_1 = [100,84,76,48,36,77,90]
exam_2 = [95,78,66,57,75,89,95]
exam_1_np = np.array(exam_1)
exam_2_np = np.array(exam_2)
average_exams = (exam_1_np+exam_2_np)/2
average_exams

array([97.5, 81. , 71. , 52.5, 55.5, 83. , 92.5])

<h4>Summation of arrays: </h4>

In [55]:
exam_1+exam_2

[100, 84, 76, 48, 36, 77, 90, 95, 78, 66, 57, 75, 89, 95]

In [56]:
exam_1_np+exam_2_np

array([195, 162, 142, 105, 111, 166, 185])

<h5>Selection elements with boolean operators on numpy array:</h5>

In [57]:
average_exams>70

array([ True,  True,  True, False, False,  True,  True])

In [58]:
average_exams[average_exams>70]

array([97.5, 81. , 71. , 83. , 92.5])

<h5>Generating numbers</h5>

In [59]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [61]:
np.linspace(-2,2,21)

array([-2. , -1.8, -1.6, -1.4, -1.2, -1. , -0.8, -0.6, -0.4, -0.2,  0. ,
        0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [62]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

<h3>Multidimensional Numpy Arrays</h3>

In [64]:
arr = np.array([3.4,3.6,3.9,4.2,4.0,3.8])
type(arr)

numpy.ndarray

<h5>Type of Numpy arrays: </h5>
<p>The Numpy arrays are defined as n-dimensional arrays. When we want to see the type of a numpy array using the type() function, we see that it is numpy.darray.</p>

In [69]:
arr = np.array([[3.4,3.6,3.9,4.2,4.0,3.8],
               [3.4,3.6,3.9,4.2,4.0,3.8],
               [3.4,3.6,3.9,4.2,4.0,3.8]])
arr

array([[3.4, 3.6, 3.9, 4.2, 4. , 3.8],
       [3.4, 3.6, 3.9, 4.2, 4. , 3.8],
       [3.4, 3.6, 3.9, 4.2, 4. , 3.8]])

<h5>Selection an element on numpy array: </h5>
<p>arr[start:end:step]</p>

In [70]:
arr = np.arange(20)
# First 7 elements:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [71]:
# Elements after the 10th index.
arr[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [72]:
# Starting from the 5th index to the 10th index.
arr[5:10]

array([5, 6, 7, 8, 9])

In [74]:
#Jumping three times from beginning.
arr[::3]

array([ 0,  3,  6,  9, 12, 15, 18])

<h5>Selection an element on array of two or more dimensions:</h5>
<p>Specify the indexes for each dimension with a comma.</p>

In [76]:
_matrix = arr.reshape(4,5)
_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
# row 2 ,column 3
_matrix[2:3,3:4]

array([[13]])

In [78]:
# Elements to the row 2 and column 3
_matrix[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])